FROM redis
# COPY redis.conf /usr/local/etc/redis/redis.conf
# COPY custom-entrypoint.sh /usr/local/bin/custom-entrypoint.sh
# ENTRYPOINT ["sh /usr/local/bin/custom-entrypoint.sh"]
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]