version: '3.7'
services: 
    web:
        build: .
        ports: 
          - "8080:8080"
    redis:
        build: ./redis
        ulimits:
            nproc: 65535
            nofile:
              soft: 20000
              hard: 40000
        sysctls:
            net.core.somaxconn: '511'

